#!/bin/bash

TITLE="League of Legends on Linux (WINE, with PBA patches, knobs and switches)"
NOTICE="Home page of the project: https://github.com/h4ndshake/leagueoflinux"

function install_app() {
  # Install additional requirements via winetricks here
  if [ -n "${TRICKS}" ]; then
    for TRICK in ${TRICKS}; do
      env WINEARCH="${WINEARCH}" WINEPREFIX="${WINEPREFIX}" "${WINETRICKS}" --unattended ${TRICK}
    done
  fi

region=$(yad --width=250 --center --on-top --align=center --title="League of Linux" --form --separator=" " --item-separator="," \
--field="Choose your region:":CB "BR,EUNE,EUW,JP,LA1,LA2,NA,OC1,RU,TR" --item-separator="," \
)
  case $region in
      BR*) install_br ;;
      EUNE*) install_eune ;;
      EUW*) install_euw ;;
      JP*) install_jp ;;
      LA1*) install_la1 ;;
      LA2*) install_la2 ;;
      NA*) install_na ;;
      OC1*) install_oc1 ;;
      RU*) install_ru ;;
      TR*) install_tr ;;
esac
}

function install_br() {
  # Modify or remove this as required by your application.
  if [ -n "${INSTALL_URL_BR}" ]; then
    # Downloads a file with progress using wget and yad
    wget "${INSTALL_URL_BR}" -O "${TMPDIR}/${INSTALL_EXE_BR}" 2>&1 | \
    perl -p -e '$| = 1; s/^.* +([0-9]+%) +([0-9,.]+[GMKB]) +([0-9hms,.]+).*$/\1\n# Downloading... \2 (\3)/' | \
    yad --progress --title="${INSTALL_EXE_BR}" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --no-escape
    # Installs the wine application
    env WINEARCH="${WINEARCH}" WINEPREFIX="${WINEPREFIX}" "${WINELOADER}" "${TMPDIR}/${INSTALL_EXE_BR}" --mode unattended 2>&1 | \
    perl -p -e '$| = 1; s/^.* +([0-9]+%) +([0-9,.]+[GMKB]) +([0-9hms,.]+).*$/\1\n# Installing... \2 (\3)/' | \
    yad --progress --progress-text="Installing League of Legends" --title="League of Linux" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --no-escape --percentage="0"
    # Removes the cached installer
    rm -v "${TMPDIR}/${INSTALL_EXE_BR}"
  fi
launch_app
}

function install_eune() {
  # Modify or remove this as required by your application.
  if [ -n "${INSTALL_URL_EUNE}" ]; then
    # Downloads a file with progress using wget and yad
    wget "${INSTALL_URL_EUNE}" -O "${TMPDIR}/${INSTALL_EXE_EUNE}" 2>&1 | \
    perl -p -e '$| = 1; s/^.* +([0-9]+%) +([0-9,.]+[GMKB]) +([0-9hms,.]+).*$/\1\n# Downloading... \2 (\3)/' | \
    yad --progress --title="${INSTALL_EXE_EUNE}" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --no-escape
    # Installs the wine application
    env WINEARCH="${WINEARCH}" WINEPREFIX="${WINEPREFIX}" "${WINELOADER}" "${TMPDIR}/${INSTALL_EXE_EUNE}" --mode unattended 2>&1 | \
    perl -p -e '$| = 1; s/^.* +([0-9]+%) +([0-9,.]+[GMKB]) +([0-9hms,.]+).*$/\1\n# Installing... \2 (\3)/' | \
    yad --progress --progress-text="Installing League of Legends" --title="League of Linux" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --no-escape --percentage="0"
    # Removes the cached installer
    rm -v "${TMPDIR}/${INSTALL_EXE_EUNE}"
  fi
launch_app
}

function install_euw() {
  # Modify or remove this as required by your application.
  if [ -n "${INSTALL_URL_EUW}" ]; then
    # Downloads a file with progress using wget and yad
    wget "${INSTALL_URL_EUW}" -O "${TMPDIR}/${INSTALL_EXE_EUW}" 2>&1 | \
    perl -p -e '$| = 1; s/^.* +([0-9]+%) +([0-9,.]+[GMKB]) +([0-9hms,.]+).*$/\1\n# Downloading... \2 (\3)/' | \
    yad --progress --title="${INSTALL_EXE_EUW}" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --no-escape
    # Installs the wine application
    env WINEARCH="${WINEARCH}" WINEPREFIX="${WINEPREFIX}" "${WINELOADER}" "${TMPDIR}/${INSTALL_EXE_EUW}" --mode unattended 2>&1 | \
    perl -p -e '$| = 1; s/^.* +([0-9]+%) +([0-9,.]+[GMKB]) +([0-9hms,.]+).*$/\1\n# Installing... \2 (\3)/' | \
    yad --progress --progress-text="Installing League of Legends" --title="League of Linux" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --no-escape --percentage="0"
    # Removes the cached installer
    rm -v "${TMPDIR}/${INSTALL_EXE_EUW}"
  fi
launch_app
}

function install_jp() {
  # Modify or remove this as required by your application.
  if [ -n "${INSTALL_URL_JP}" ]; then
    # Downloads a file with progress using wget and yad
    wget "${INSTALL_URL_JP}" -O "${TMPDIR}/${INSTALL_EXE_JP}" 2>&1 | \
    perl -p -e '$| = 1; s/^.* +([0-9]+%) +([0-9,.]+[GMKB]) +([0-9hms,.]+).*$/\1\n# Downloading... \2 (\3)/' | \
    yad --progress --title="${INSTALL_EXE_JP}" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --no-escape
    # Installs the wine application
    env WINEARCH="${WINEARCH}" WINEPREFIX="${WINEPREFIX}" "${WINELOADER}" "${TMPDIR}/${INSTALL_EXE_JP}" --mode unattended 2>&1 | \
    perl -p -e '$| = 1; s/^.* +([0-9]+%) +([0-9,.]+[GMKB]) +([0-9hms,.]+).*$/\1\n# Installing... \2 (\3)/' | \
    yad --progress --progress-text="Installing League of Legends" --title="League of Linux" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --no-escape --percentage="0"
    # Removes the cached installer
    rm -v "${TMPDIR}/${INSTALL_EXE_JP}"
  fi
launch_app
}

function install_la1() {
  # Modify or remove this as required by your application.
  if [ -n "${INSTALL_URL_LA1}" ]; then
    # Downloads a file with progress using wget and yad
    wget "${INSTALL_URL_LA1}" -O "${TMPDIR}/${INSTALL_EXE_LA1}" 2>&1 | \
    perl -p -e '$| = 1; s/^.* +([0-9]+%) +([0-9,.]+[GMKB]) +([0-9hms,.]+).*$/\1\n# Downloading... \2 (\3)/' | \
    yad --progress --title="${INSTALL_EXE_LA1}" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --no-escape
    # Installs the wine application
    env WINEARCH="${WINEARCH}" WINEPREFIX="${WINEPREFIX}" "${WINELOADER}" "${TMPDIR}/${INSTALL_EXE_LA1}" --mode unattended 2>&1 | \
    perl -p -e '$| = 1; s/^.* +([0-9]+%) +([0-9,.]+[GMKB]) +([0-9hms,.]+).*$/\1\n# Installing... \2 (\3)/' | \
    yad --progress --progress-text="Installing League of Legends" --title="League of Linux" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --no-escape --percentage="0"
    # Removes the cached installer
    rm -v "${TMPDIR}/${INSTALL_EXE_LA1}"
  fi
launch_app
}

function install_la2() {
  # Modify or remove this as required by your application.
  if [ -n "${INSTALL_URL_LA2}" ]; then
    # Downloads a file with progress using wget and yad
    wget "${INSTALL_URL_LA2}" -O "${TMPDIR}/${INSTALL_EXE_LA2}" 2>&1 | \
    perl -p -e '$| = 1; s/^.* +([0-9]+%) +([0-9,.]+[GMKB]) +([0-9hms,.]+).*$/\1\n# Downloading... \2 (\3)/' | \
    yad --progress --title="${INSTALL_EXE_LA2}" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --no-escape
    # Installs the wine application
    env WINEARCH="${WINEARCH}" WINEPREFIX="${WINEPREFIX}" "${WINELOADER}" "${TMPDIR}/${INSTALL_EXE_LA2}" --mode unattended 2>&1 | \
    perl -p -e '$| = 1; s/^.* +([0-9]+%) +([0-9,.]+[GMKB]) +([0-9hms,.]+).*$/\1\n# Installing... \2 (\3)/' | \
    yad --progress --progress-text="Installing League of Legends" --title="League of Linux" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --no-escape --percentage="0"
    # Removes the cached installer
    rm -v "${TMPDIR}/${INSTALL_EXE_LA2}"
  fi
launch_app
}

function install_na() {
  # Modify or remove this as required by your application.
  if [ -n "${INSTALL_URL_NA}" ]; then
    # Downloads a file with progress using wget and yad
    wget "${INSTALL_URL_NA}" -O "${TMPDIR}/${INSTALL_EXE_NA}" 2>&1 | \
    perl -p -e '$| = 1; s/^.* +([0-9]+%) +([0-9,.]+[GMKB]) +([0-9hms,.]+).*$/\1\n# Downloading... \2 (\3)/' | \
    yad --progress --title="${INSTALL_EXE_NA}" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --no-escape
    # Installs the wine application
    env WINEARCH="${WINEARCH}" WINEPREFIX="${WINEPREFIX}" "${WINELOADER}" "${TMPDIR}/${INSTALL_EXE_NA}" --mode unattended 2>&1 | \
    perl -p -e '$| = 1; s/^.* +([0-9]+%) +([0-9,.]+[GMKB]) +([0-9hms,.]+).*$/\1\n# Installing... \2 (\3)/' | \
    yad --progress --progress-text="Installing League of Legends" --title="League of Linux" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --no-escape --percentage="0"
    # Removes the cached installer
    rm -v "${TMPDIR}/${INSTALL_EXE_NA}"
  fi
launch_app
}

function install_oc1() {
  # Modify or remove this as required by your application.
  if [ -n "${INSTALL_URL_OC1}" ]; then
    # Downloads a file with progress using wget and yad
    wget "${INSTALL_URL_OC1}" -O "${TMPDIR}/${INSTALL_EXE_OC1}" 2>&1 | \
    perl -p -e '$| = 1; s/^.* +([0-9]+%) +([0-9,.]+[GMKB]) +([0-9hms,.]+).*$/\1\n# Downloading... \2 (\3)/' | \
    yad --progress --title="${INSTALL_EXE_OC1}" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --no-escape
    # Installs the wine application
    env WINEARCH="${WINEARCH}" WINEPREFIX="${WINEPREFIX}" "${WINELOADER}" "${TMPDIR}/${INSTALL_EXE_OC1}" --mode unattended 2>&1 | \
    perl -p -e '$| = 1; s/^.* +([0-9]+%) +([0-9,.]+[GMKB]) +([0-9hms,.]+).*$/\1\n# Installing... \2 (\3)/' | \
    yad --progress --progress-text="Installing League of Legends" --title="League of Linux" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --no-escape --percentage="0"
    # Removes the cached installer
    rm -v "${TMPDIR}/${INSTALL_EXE_OC1}"
  fi
launch_app
}

function install_ru() {
  # Modify or remove this as required by your application.
  if [ -n "${INSTALL_URL_RU}" ]; then
    # Downloads a file with progress using wget and yad
    wget "${INSTALL_URL_RU}" -O "${TMPDIR}/${INSTALL_EXE_RU}" 2>&1 | \
    perl -p -e '$| = 1; s/^.* +([0-9]+%) +([0-9,.]+[GMKB]) +([0-9hms,.]+).*$/\1\n# Downloading... \2 (\3)/' | \
    yad --progress --title="${INSTALL_EXE_RU}" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --no-escape
    # Installs the wine application
    env WINEARCH="${WINEARCH}" WINEPREFIX="${WINEPREFIX}" "${WINELOADER}" "${TMPDIR}/${INSTALL_EXE_RU}" --mode unattended 2>&1 | \
    perl -p -e '$| = 1; s/^.* +([0-9]+%) +([0-9,.]+[GMKB]) +([0-9hms,.]+).*$/\1\n# Installing... \2 (\3)/' | \
    yad --progress --progress-text="Installing League of Legends" --title="League of Linux" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --no-escape --percentage="0"
    # Removes the cached installer
    rm -v "${TMPDIR}/${INSTALL_EXE_RU}"
  fi
launch_app
}

function install_tr() {
  # Modify or remove this as required by your application.
  if [ -n "${INSTALL_URL_TR}" ]; then
    # Downloads a file with progress using wget and yad
    wget "${INSTALL_URL_TR}" -O "${TMPDIR}/${INSTALL_EXE_TR}" 2>&1 | \
    perl -p -e '$| = 1; s/^.* +([0-9]+%) +([0-9,.]+[GMKB]) +([0-9hms,.]+).*$/\1\n# Downloading... \2 (\3)/' | \
    yad --progress --title="${INSTALL_EXE_TR}" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --no-escape
    # Installs the wine application
    env WINEARCH="${WINEARCH}" WINEPREFIX="${WINEPREFIX}" "${WINELOADER}" "${TMPDIR}/${INSTALL_EXE_TR}" --mode unattended 2>&1 | \
    perl -p -e '$| = 1; s/^.* +([0-9]+%) +([0-9,.]+[GMKB]) +([0-9hms,.]+).*$/\1\n# Installing... \2 (\3)/' | \
    yad --progress --progress-text="Installing League of Legends" --title="League of Linux" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --no-escape --percentage="0"
    # Removes the cached installer
    rm -v "${TMPDIR}/${INSTALL_EXE_TR}"
  fi
launch_app
}

function launch_app() {
  # If we don't change into the program directory some assets may not be found
  cd "${WINE_DIR}"

  # Only use virtual desktop if it has been requested and we're running Xorg
  if [ "${XDG_SESSION_TYPE}" == "x11" ] && [ "${VIRTDESKTOP}" == "1" ]; then
    # Get the native resolution of the primary display.
    # Creating a virtual desktop the same size will eliminate bugs when
    # switching from fullscreen to windowed mode.
    NATIVE_RES=$(xrandr -q | grep primary | cut -d' ' -f4 | cut -d'+' -f1)
    env WINEARCH="${WINEARCH}" WINEPREFIX="${WINEPREFIX}" "${WINELOADER}" explorer /desktop="virtual","${NATIVE_RES}" "${WINE_EXE}" $@
  else
    env WINEARCH="${WINEARCH}" WINEPREFIX="${WINEPREFIX}" "${WINELOADER}" "${WINE_EXE}" $@
  fi
}

function prepend_dir() {
  local var="$1"
  local dir="$2"
  if [ -d "$dir" ]; then
    eval "export $var=\"\$dir\${$var:+:\$$var}\""
  fi
}

function append_dir() {
  local var="$1"
  local dir="$2"
  if [ -d "$dir" ]; then
    eval "export $var=\"\${$var:+\$$var:}\$dir\""
  fi
}

# Get the executable we're being asked to launch
if [ -n "${1}" ]; then
  WINE_EXE="${1}"
  WINE_DIR=$(dirname "${WINE_EXE}")
else
  echo "ERROR! I need an executable that I should launch. Exitting here."
  exit 1
fi

# If we've been given and installer URL derive the filename
if [ -n "${INSTALL_URL_BR}" ]; then
  INSTALL_EXE_BR=$(basename "${INSTALL_URL_BR}")
fi

if [ -n "${INSTALL_URL_EUNE}" ]; then
  INSTALL_EXE_EUNE=$(basename "${INSTALL_URL_EUNE}")
fi

if [ -n "${INSTALL_URL_EUW}" ]; then
  INSTALL_EXE_EUW=$(basename "${INSTALL_URL_EUW}")
fi

if [ -n "${INSTALL_URL_JP}" ]; then
  INSTALL_EXE_JP=$(basename "${INSTALL_URL_JP}")
fi

if [ -n "${INSTALL_URL_LA1}" ]; then
  INSTALL_EXE_LA1=$(basename "${INSTALL_URL_LA1}")
fi

if [ -n "${INSTALL_URL_LA2}" ]; then
  INSTALL_EXE_LA2=$(basename "${INSTALL_URL_LA2}")
fi

if [ -n "${INSTALL_URL_NA}" ]; then
  INSTALL_EXE_NA=$(basename "${INSTALL_URL_NA}")
fi

if [ -n "${INSTALL_URL_OC1}" ]; then
  INSTALL_EXE_OC1=$(basename "${INSTALL_URL_OC1}")
fi

if [ -n "${INSTALL_URL_RU}" ]; then
  INSTALL_EXE_RU=$(basename "${INSTALL_URL_RU}")
fi

if [ -n "${INSTALL_URL_TR}" ]; then
  INSTALL_EXE_TR=$(basename "${INSTALL_URL_TR}")
fi

# On Fedora $SNAP is under /var and there is some magic to map it to /snap.
# # We need to handle that case and reset $SNAP
SNAP=`echo $SNAP | sed -e "s|/var/lib/snapd||g"`

export GTK_MODULES=""

if [ -n "${DLLOVERRIDES}" ]; then
  export WINEDLLOVERRIDES="${DLLOVERRIDES}"
fi

if [ "$SNAP_ARCH" = "amd64" ]; then
  export WINEARCH=win64
  export WINE=wine64
  export WINELOADER=$SNAP/bin/wine64
  export WINEDLLPATH=$SNAP/lib64/wine/fakedlls
  export ARCH="x86_64-linux-gnu"
else
  echo "Host architecture ($SNAP_ARCH) unsupported."
  exit 1
fi

export WINEVERPATH=$SNAP
export WINESERVER=$SNAP/bin/wineserver
export WINETRICKS=$SNAP/bin/winetricks
export winepath=$SNAP/bin/winepath
export WINEPREFIX="$SNAP_USER_COMMON/.wine"

export WINEDEBUG=-all
export LD_LIBRARY_PATH="$SNAP/lib/$ARCH:$SNAP/lib:$SNAP/usr/lib/$ARCH:$SNAP/usr/lib"
if [ "$SNAP_ARCH" = "amd64" ]; then
  append_dir LD_LIBRARY_PATH $SNAP/lib64
  append_dir LD_LIBRARY_PATH $SNAP/lib/i386-linux-gnu
  append_dir LD_LIBRARY_PATH $SNAP/usr/lib/i386-linux-gnu
fi

# PBA knobs and switches
export __PBA_CB_HEAP=64
export __PBA_GEO_HEAP=256

# Enables Esync
export WINEESYNC=1

# XKB config
export XKB_CONFIG_ROOT=$SNAP/usr/share/X11/xkb

# Give XOpenIM a chance to locate locale data.
# This is required for text input to work in SDL2 games.
export XLOCALEDIR=$SNAP/usr/share/X11/locale

# Set XCursors path
export XCURSOR_PATH=$SNAP/usr/share/icons

# SAMBA Libs for ntlm_auth to function
append_dir LD_LIBRARY_PATH $SNAP/usr/lib/$ARCH/samba
[ "$SNAP_ARCH" = "amd64" ] && append_dir LD_LIBRARY_PATH $SNAP/usr/lib/i386-linux-gnu/samba

# Mesa Libs for OpenGL support
append_dir LD_LIBRARY_PATH $SNAP/usr/lib/$ARCH/mesa
append_dir LD_LIBRARY_PATH $SNAP/usr/lib/$ARCH/mesa-egl
[ "$SNAP_ARCH" = "amd64" ] && append_dir LD_LIBRARY_PATH $SNAP/usr/lib/i386-linux-gnu/mesa
[ "$SNAP_ARCH" = "amd64" ] && append_dir LD_LIBRARY_PATH $SNAP/usr/lib/i386-linux-gnu/mesa-egl

# Tell libGL where to find the drivers
export LIBGL_DRIVERS_PATH=$SNAP/usr/lib/$ARCH/dri
[ "$SNAP_ARCH" = "amd64" ] && append_dir LIBGL_DRIVERS_PATH $SNAP/usr/lib/i386-linux-gnu/dri
append_dir LD_LIBRARY_PATH $LIBGL_DRIVERS_PATH

# Workaround in snapd for proprietary nVidia drivers mounts the drivers in
# /var/lib/snapd/lib/gl that needs to be in LD_LIBRARY_PATH
# Without that OpenGL using apps do not work with the nVidia drivers.
# Ref.: https://bugs.launchpad.net/snappy/+bug/1588192
append_dir LD_LIBRARY_PATH /var/lib/snapd/lib/gl

# Pulseaudio export
append_dir LD_LIBRARY_PATH $SNAP/usr/lib/$ARCH/pulseaudio
[ "$SNAP_ARCH" = "amd64" ] && append_dir LD_LIBRARY_PATH $SNAP/usr/lib/i386-linux-gnu/pulseaudio

# EGL vendor files on glvnd enabled systems
[ -d /var/lib/snapd/lib/glvnd/egl_vendor.d ] && \
append_dir __EGL_VENDOR_LIBRARY_DIRS /var/lib/snapd/lib/glvnd/egl_vendor.d

# Tell GStreamer where to find its plugins
export GST_PLUGIN_PATH=$SNAP/usr/lib/$ARCH/gstreamer-1.0
export GST_PLUGIN_SYSTEM_PATH=$SNAP/usr/lib/$ARCH/gstreamer-1.0
# gst plugin scanner doesn't install in the correct path: https://github.com/ubuntu/snapcraft-desktop-helpers/issues/43
export GST_PLUGIN_SCANNER=$SNAP/usr/lib/$ARCH/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner

# XDG Config
prepend_dir XDG_CONFIG_DIRS $SNAP/etc/xdg

# Define snaps' own data dir
prepend_dir XDG_DATA_DIRS $SNAP/usr/share
prepend_dir XDG_DATA_DIRS $SNAP_USER_COMMON

export HOME=$SNAP_USER_COMMON

# Set XDG_DATA_HOME to local path
export XDG_DATA_HOME=$SNAP_USER_COMMON/.local/share
mkdir -p $XDG_DATA_HOME

# Workaround for GLib < 2.53.2 not searching for schemas in $XDG_DATA_HOME:
#   https://bugzilla.gnome.org/show_bug.cgi?id=741335
prepend_dir XDG_DATA_DIRS $XDG_DATA_HOME

# Set cache folder to local path
export XDG_CACHE_HOME=$SNAP_USER_COMMON/.cache
mkdir -p $XDG_CACHE_HOME

# Set config folder to local path
export XDG_CONFIG_HOME=$SNAP_USER_COMMON/.config
mkdir -p $XDG_CONFIG_HOME

# Create $XDG_RUNTIME_DIR if not exists (to be removed when LP: #1656340 is fixed)
mkdir -p $XDG_RUNTIME_DIR -m 700

# Make PulseAudio socket available inside the snap-specific $XDG_RUNTIME_DIR
    pulsenative="pulse/native"
    pulseaudio_sockpath="$XDG_RUNTIME_DIR/../$pulsenative"
    if [ -S "$pulseaudio_sockpath" ]; then
        export PULSE_SERVER="unix:${pulseaudio_sockpath}"
    fi

# Font Config and themes
export FONTCONFIG_PATH=$SNAP/etc/fonts/conf.d
#export FONTCONFIG_FILE=$XDG_CONFIG_HOME/fontconfig/fonts.conf

# Gdk-pixbuf loaders
export GDK_PIXBUF_MODULE_FILE=$XDG_CACHE_HOME/gdk-pixbuf-loaders.cache
export GDK_PIXBUF_MODULEDIR=$SNAP/usr/lib/$ARCH/gdk-pixbuf-2.0/2.10.0/loaders
if [ -f $SNAP/usr/lib/$ARCH/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders ] && [ ! -f "${GDK_PIXBUF_MODULE_FILE}" ]; then
  $SNAP/usr/lib/$ARCH/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders > $GDK_PIXBUF_MODULE_FILE
fi

# Stop wine from updating $WINEPREFIX automatically
if [ -f "${WINEPREFIX}/.update-timestamp" ]; then
  chkstmp=$(grep disable "${WINEPREFIX}/.update-timestamp" | wc -l)
  if [ $chkstmp -eq 0 ]; then
    echo "disable" > "${WINEPREFIX}/.update-timestamp"
  fi
fi

# Opt out of winetricks metrics - we ninja this to avoid dialogs
if [ ! -f "${XDG_CACHE_HOME}/winetricks/track_usage" ]; then
  mkdir -p "${XDG_CACHE_HOME}/winetricks"
  echo 0 > "${XDG_CACHE_HOME}/winetricks/track_usage"
fi

# Launch wineboot/winecfg/winetricks if requested.
# If the executable exists then launch it otherwise install it then lauch it.
if [[ ${WINE_EXE} = *"winecfg"* ]] || [[ ${WINE_EXE} = *"wineboot"* ]] || [[ ${WINE_EXE} = *"winetricks"* ]]; then
  "${WINE_EXE}" "$@"
elif [ -e "${WINE_EXE}" ]; then
  # Notification
  notify-send --icon "${SNAP}/meta/gui/icon.ico" --expire-time=15000 "${TITLE}" "${NOTICE}"
  launch_app
else
  # Notification
  notify-send --icon "${SNAP}/meta/gui/icon.ico" --expire-time=15000 "${TITLE}" "${NOTICE}"
  install_app
fi
